#!/bin/bash

# Create a build-directory
mkdir build

# Go to the build-directory
cd build

# CMake creates a Makefile based on CMakeLists.txt
cmake ../

# Make the Makefile using four threads (the number of cores in a standard comp)
make -j4
