#!/bin/bash                                                                     

# Job name:                                                                     
#SBATCH --job-name=VMC_2D_6P_1p0w                                               
#                                                                               
# Project:                                                                      
#SBATCH --account=nn2977k                                                       
#                                                                               
# Wall clock limit:                                                             
#SBATCH --time=01:00:00                                                         
#                                                                               
# Max memory usage:                                                             
#SBATCH --mem-per-cpu=3800                                                      
#                                                                               
# Specify normal partition                                                      
#SBATCH --partition=normal                                                      
#                                                                               
# Number of tasks (MPI ranks):                                                  
#SBATCH --ntasks=128                                                            
#                                                                               
# Number of nodes                                                               
#SBATCH --nodes=8                                                                                                                                                                                                
#                                                                               
# Set output file name                                                          
#SBATCH --output=data/int1/abel/VMC_2D_6P_1p0w.out                              
#                                                                               
# Send mail with info:                                                          
#SBATCH --mail-type=BEGIN,TIME_LIMIT_10,END                                     

## Set up job environment:                                                      
source /cluster/bin/jobsetup
module purge   # clear any inherited modules                                    
set -o errexit # exit on errors                                                 

module load openmpi.gnu

mpirun build/vmc configs/2D_6P_1p000000w

